import { TemplateRef, ElementRef } from '@angular/core';
import { FormitemComponent } from '../formitem/formitem.component';
import { ValueAccessorDirective } from '../../directives/valueaccessor.directive';
import { type AriaAttributes } from '../../types';
import * as i0 from "@angular/core";
import * as i1 from "../../directives/valueaccessor.directive";
export declare class TextareaComponent extends FormitemComponent {
    readonly valueAccessor: ValueAccessorDirective<string>;
    private configService;
    readonly id: import("@angular/core").InputSignal<string>;
    readonly name: import("@angular/core").InputSignal<string>;
    readonly disabled: import("@angular/core").ModelSignal<boolean>;
    readonly label: import("@angular/core").InputSignal<string>;
    readonly placeholder: import("@angular/core").InputSignal<string>;
    readonly rows: import("@angular/core").InputSignalWithTransform<number, unknown>;
    readonly cols: import("@angular/core").InputSignalWithTransform<number, unknown>;
    readonly required: import("@angular/core").ModelSignal<boolean>;
    readonly hasCounter: import("@angular/core").InputSignalWithTransform<boolean, unknown>;
    readonly minLength: import("@angular/core").InputSignalWithTransform<number, unknown>;
    readonly maxLength: import("@angular/core").InputSignalWithTransform<number, unknown>;
    readonly readonly: import("@angular/core").InputSignalWithTransform<boolean, unknown>;
    readonly counterLabel: import("@angular/core").InputSignal<string>;
    readonly counterFromLabel: import("@angular/core").InputSignal<string>;
    readonly counterLimitReachedMessage: import("@angular/core").InputSignal<string>;
    readonly ariaAttributes: import("@angular/core").InputSignal<AriaAttributes>;
    readonly autogrow: import("@angular/core").InputSignalWithTransform<boolean, unknown>;
    readonly toggletip: import("@angular/core").InputSignal<string>;
    readonly toggletipLabel: import("@angular/core").InputSignal<string>;
    readonly toggletipCloseLabel: import("@angular/core").InputSignal<string>;
    readonly toggletipTemplate: import("@angular/core").InputSignal<TemplateRef<unknown>>;
    readonly requiredSign: import("@angular/core").ModelSignal<string>;
    readonly requiredSignTitleAttr: import("@angular/core").InputSignal<string>;
    readonly optionalText: import("@angular/core").ModelSignal<string>;
    readonly visuallyHiddenLabel: import("@angular/core").InputSignalWithTransform<boolean, unknown>;
    readonly input: import("@angular/core").Signal<ElementRef<any>>;
    protected externalId: string;
    protected get containerCssClasses(): string;
    private innerValue?;
    /** Inserted by Angular inject() migration for backwards compatibility */
    constructor(...args: unknown[]);
    protected get charCount(): number;
    protected get readOutCounter(): boolean;
    protected get hasCounterLimitReached(): boolean;
    protected get inputAriaAttributes(): AriaAttributes;
    protected get cssInputClass(): string;
    get value(): string;
    set value(value: string);
    protected onFocusout(event: FocusEvent): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<TextareaComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TextareaComponent, "drv-textarea", never, { "id": { "alias": "id"; "required": false; "isSignal": true; }; "name": { "alias": "name"; "required": false; "isSignal": true; }; "disabled": { "alias": "disabled"; "required": false; "isSignal": true; }; "label": { "alias": "label"; "required": false; "isSignal": true; }; "placeholder": { "alias": "placeholder"; "required": false; "isSignal": true; }; "rows": { "alias": "rows"; "required": false; "isSignal": true; }; "cols": { "alias": "cols"; "required": false; "isSignal": true; }; "required": { "alias": "required"; "required": false; "isSignal": true; }; "hasCounter": { "alias": "hasCounter"; "required": false; "isSignal": true; }; "minLength": { "alias": "minLength"; "required": false; "isSignal": true; }; "maxLength": { "alias": "maxLength"; "required": false; "isSignal": true; }; "readonly": { "alias": "readonly"; "required": false; "isSignal": true; }; "counterLabel": { "alias": "counterLabel"; "required": false; "isSignal": true; }; "counterFromLabel": { "alias": "counterFromLabel"; "required": false; "isSignal": true; }; "counterLimitReachedMessage": { "alias": "counterLimitReachedMessage"; "required": false; "isSignal": true; }; "ariaAttributes": { "alias": "ariaAttributes"; "required": false; "isSignal": true; }; "autogrow": { "alias": "autogrow"; "required": false; "isSignal": true; }; "toggletip": { "alias": "toggletip"; "required": false; "isSignal": true; }; "toggletipLabel": { "alias": "toggletipLabel"; "required": false; "isSignal": true; }; "toggletipCloseLabel": { "alias": "toggletipCloseLabel"; "required": false; "isSignal": true; }; "toggletipTemplate": { "alias": "toggletipTemplate"; "required": false; "isSignal": true; }; "requiredSign": { "alias": "requiredSign"; "required": false; "isSignal": true; }; "requiredSignTitleAttr": { "alias": "requiredSignTitleAttr"; "required": false; "isSignal": true; }; "optionalText": { "alias": "optionalText"; "required": false; "isSignal": true; }; "visuallyHiddenLabel": { "alias": "visuallyHiddenLabel"; "required": false; "isSignal": true; }; }, { "disabled": "disabledChange"; "required": "requiredChange"; "requiredSign": "requiredSignChange"; "optionalText": "optionalTextChange"; }, never, never, true, [{ directive: typeof i1.ValueAccessorDirective; inputs: {}; outputs: {}; }]>;
}
