import { TemplateRef, AfterContentInit, ElementRef } from '@angular/core';
import { MaskitoOptions } from '@maskito/core';
import { FormitemComponent } from '../formitem/formitem.component';
import { ValueAccessorDirective } from '../../directives/valueaccessor.directive';
import { type AriaAttributes } from '../../types';
import { type IconOnlyType } from '../button/button.component';
import * as i0 from "@angular/core";
import * as i1 from "../../directives/valueaccessor.directive";
export type SearchbarVariant = 'default' | 'mini' | 'icon-only';
export declare class SearchbarComponent extends FormitemComponent implements AfterContentInit {
    readonly valueAccessor: ValueAccessorDirective<string>;
    private configService;
    readonly label: import("@angular/core").InputSignal<string>;
    readonly buttonText: import("@angular/core").InputSignal<string>;
    readonly buttonTextClear: import("@angular/core").InputSignal<string>;
    readonly placeholder: import("@angular/core").InputSignal<string>;
    readonly disabled: import("@angular/core").ModelSignal<boolean>;
    readonly required: import("@angular/core").ModelSignal<boolean>;
    readonly buttonDisabled: import("@angular/core").InputSignalWithTransform<boolean, unknown>;
    readonly variant: import("@angular/core").InputSignal<SearchbarVariant>;
    readonly toggletip: import("@angular/core").InputSignal<string>;
    readonly toggletipLabel: import("@angular/core").InputSignal<string>;
    readonly toggletipCloseLabel: import("@angular/core").InputSignal<string>;
    readonly toggletipTemplate: import("@angular/core").InputSignal<TemplateRef<unknown>>;
    readonly requiredSign: import("@angular/core").ModelSignal<string>;
    readonly requiredSignTitleAttr: import("@angular/core").InputSignal<string>;
    readonly optionalText: import("@angular/core").ModelSignal<string>;
    readonly visuallyHiddenLabel: import("@angular/core").InputSignalWithTransform<boolean, unknown>;
    readonly maskOptions: import("@angular/core").InputSignal<MaskitoOptions>;
    readonly keyboardShortcut: import("@angular/core").InputSignal<string>;
    readonly input: import("@angular/core").Signal<ElementRef<HTMLInputElement>>;
    readonly searched: import("@angular/core").OutputEmitterRef<string>;
    readonly combobox: import("@angular/core").Signal<any>;
    protected externalId: string;
    private innerValue?;
    /** Inserted by Angular inject() migration for backwards compatibility */
    constructor(...args: unknown[]);
    protected get containerCssClasses(): string;
    protected get cssWrapperClass(): string;
    protected get cssBgClass(): string;
    protected get inputAriaAttributes(): AriaAttributes;
    protected get iconOnly(): IconOnlyType;
    get value(): string;
    set value(value: string);
    protected onFocusout(event: FocusEvent): void;
    /** @internal */
    ngAfterContentInit(): void;
    protected clickHandler(): void;
    protected clickClearHandler(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SearchbarComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SearchbarComponent, "drv-searchbar", never, { "label": { "alias": "label"; "required": true; "isSignal": true; }; "buttonText": { "alias": "buttonText"; "required": true; "isSignal": true; }; "buttonTextClear": { "alias": "buttonTextClear"; "required": true; "isSignal": true; }; "placeholder": { "alias": "placeholder"; "required": false; "isSignal": true; }; "disabled": { "alias": "disabled"; "required": false; "isSignal": true; }; "required": { "alias": "required"; "required": false; "isSignal": true; }; "buttonDisabled": { "alias": "buttonDisabled"; "required": false; "isSignal": true; }; "variant": { "alias": "variant"; "required": false; "isSignal": true; }; "toggletip": { "alias": "toggletip"; "required": false; "isSignal": true; }; "toggletipLabel": { "alias": "toggletipLabel"; "required": false; "isSignal": true; }; "toggletipCloseLabel": { "alias": "toggletipCloseLabel"; "required": false; "isSignal": true; }; "toggletipTemplate": { "alias": "toggletipTemplate"; "required": false; "isSignal": true; }; "requiredSign": { "alias": "requiredSign"; "required": false; "isSignal": true; }; "requiredSignTitleAttr": { "alias": "requiredSignTitleAttr"; "required": false; "isSignal": true; }; "optionalText": { "alias": "optionalText"; "required": false; "isSignal": true; }; "visuallyHiddenLabel": { "alias": "visuallyHiddenLabel"; "required": false; "isSignal": true; }; "maskOptions": { "alias": "maskOptions"; "required": false; "isSignal": true; }; "keyboardShortcut": { "alias": "keyboardShortcut"; "required": false; "isSignal": true; }; }, { "disabled": "disabledChange"; "required": "requiredChange"; "requiredSign": "requiredSignChange"; "optionalText": "optionalTextChange"; "searched": "searched"; }, ["combobox"], ["drv-combobox"], true, [{ directive: typeof i1.ValueAccessorDirective; inputs: {}; outputs: {}; }]>;
}
