import { TemplateRef, ElementRef } from '@angular/core';
import { MaskitoOptions } from '@maskito/core';
import { FormitemComponent } from '../formitem/formitem.component';
import { ValueAccessorDirective } from '../../directives/valueaccessor.directive';
import { type AriaAttributes } from '../../types';
import * as i0 from "@angular/core";
import * as i1 from "../../directives/valueaccessor.directive";
export type TextInputType = 'text' | 'search' | 'url' | 'tel' | 'email' | 'number' | 'password' | 'date' | 'month' | 'week' | 'time' | 'datetime-local' | 'hidden';
export type TextInputMode = 'none' | 'text' | 'tel' | 'url' | 'email' | 'numeric' | 'decimal' | 'search';
export type TextInputAlign = 'start' | 'end';
export declare class TextinputComponent extends FormitemComponent {
    private document;
    readonly valueAccessor: ValueAccessorDirective<string>;
    private configService;
    readonly id: import("@angular/core").InputSignal<string>;
    readonly type: import("@angular/core").InputSignal<TextInputType>;
    readonly name: import("@angular/core").InputSignal<string>;
    readonly disabled: import("@angular/core").ModelSignal<boolean>;
    readonly label: import("@angular/core").InputSignal<string>;
    readonly placeholder: import("@angular/core").InputSignal<string>;
    readonly required: import("@angular/core").ModelSignal<boolean>;
    readonly hasCounter: import("@angular/core").InputSignalWithTransform<boolean, unknown>;
    readonly minLength: import("@angular/core").InputSignalWithTransform<number, unknown>;
    readonly maxLength: import("@angular/core").InputSignalWithTransform<number, unknown>;
    readonly readonly: import("@angular/core").InputSignalWithTransform<boolean, unknown>;
    readonly minDate: import("@angular/core").InputSignal<string | Date>;
    readonly maxDate: import("@angular/core").InputSignal<string | Date>;
    readonly stepDate: import("@angular/core").InputSignalWithTransform<number, unknown>;
    readonly autocomplete: import("@angular/core").InputSignal<string>;
    readonly counterLabel: import("@angular/core").InputSignal<string>;
    readonly counterFromLabel: import("@angular/core").InputSignal<string>;
    readonly counterLimitReachedMessage: import("@angular/core").InputSignal<string>;
    readonly ariaAttributes: import("@angular/core").InputSignal<AriaAttributes>;
    readonly toggletip: import("@angular/core").InputSignal<string>;
    readonly toggletipLabel: import("@angular/core").InputSignal<string>;
    readonly toggletipCloseLabel: import("@angular/core").InputSignal<string>;
    readonly toggletipTemplate: import("@angular/core").InputSignal<TemplateRef<unknown>>;
    readonly requiredSign: import("@angular/core").ModelSignal<string>;
    readonly requiredSignTitleAttr: import("@angular/core").InputSignal<string>;
    readonly optionalText: import("@angular/core").ModelSignal<string>;
    readonly visuallyHiddenLabel: import("@angular/core").InputSignalWithTransform<boolean, unknown>;
    readonly maskOptions: import("@angular/core").InputSignal<MaskitoOptions>;
    readonly inputMode: import("@angular/core").InputSignal<TextInputMode>;
    readonly textAlign: import("@angular/core").InputSignal<TextInputAlign>;
    readonly input: import("@angular/core").Signal<ElementRef<HTMLInputElement>>;
    readonly inputFieldMaxWidth: import("@angular/core").InputSignal<string>;
    protected externalId: string;
    private innerValue;
    /** Inserted by Angular inject() migration for backwards compatibility */
    constructor(...args: unknown[]);
    protected get containerCssClasses(): string;
    protected get charCount(): number;
    protected get readOutCounter(): boolean;
    protected get hasCounterLimitReached(): boolean;
    protected get inputAriaAttributes(): AriaAttributes;
    protected get cssInputClass(): string;
    get value(): string;
    set value(value: string);
    protected onFocusout(event: FocusEvent): void;
    protected stringFromDate(input: string | Date): string;
    static ɵfac: i0.ɵɵFactoryDeclaration<TextinputComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TextinputComponent, "drv-textinput", never, { "id": { "alias": "id"; "required": false; "isSignal": true; }; "type": { "alias": "type"; "required": false; "isSignal": true; }; "name": { "alias": "name"; "required": false; "isSignal": true; }; "disabled": { "alias": "disabled"; "required": false; "isSignal": true; }; "label": { "alias": "label"; "required": false; "isSignal": true; }; "placeholder": { "alias": "placeholder"; "required": false; "isSignal": true; }; "required": { "alias": "required"; "required": false; "isSignal": true; }; "hasCounter": { "alias": "hasCounter"; "required": false; "isSignal": true; }; "minLength": { "alias": "minLength"; "required": false; "isSignal": true; }; "maxLength": { "alias": "maxLength"; "required": false; "isSignal": true; }; "readonly": { "alias": "readonly"; "required": false; "isSignal": true; }; "minDate": { "alias": "minDate"; "required": false; "isSignal": true; }; "maxDate": { "alias": "maxDate"; "required": false; "isSignal": true; }; "stepDate": { "alias": "stepDate"; "required": false; "isSignal": true; }; "autocomplete": { "alias": "autocomplete"; "required": false; "isSignal": true; }; "counterLabel": { "alias": "counterLabel"; "required": false; "isSignal": true; }; "counterFromLabel": { "alias": "counterFromLabel"; "required": false; "isSignal": true; }; "counterLimitReachedMessage": { "alias": "counterLimitReachedMessage"; "required": false; "isSignal": true; }; "ariaAttributes": { "alias": "ariaAttributes"; "required": false; "isSignal": true; }; "toggletip": { "alias": "toggletip"; "required": false; "isSignal": true; }; "toggletipLabel": { "alias": "toggletipLabel"; "required": false; "isSignal": true; }; "toggletipCloseLabel": { "alias": "toggletipCloseLabel"; "required": false; "isSignal": true; }; "toggletipTemplate": { "alias": "toggletipTemplate"; "required": false; "isSignal": true; }; "requiredSign": { "alias": "requiredSign"; "required": false; "isSignal": true; }; "requiredSignTitleAttr": { "alias": "requiredSignTitleAttr"; "required": false; "isSignal": true; }; "optionalText": { "alias": "optionalText"; "required": false; "isSignal": true; }; "visuallyHiddenLabel": { "alias": "visuallyHiddenLabel"; "required": false; "isSignal": true; }; "maskOptions": { "alias": "maskOptions"; "required": false; "isSignal": true; }; "inputMode": { "alias": "inputMode"; "required": false; "isSignal": true; }; "textAlign": { "alias": "textAlign"; "required": false; "isSignal": true; }; "inputFieldMaxWidth": { "alias": "inputFieldMaxWidth"; "required": false; "isSignal": true; }; }, { "disabled": "disabledChange"; "required": "requiredChange"; "requiredSign": "requiredSignChange"; "optionalText": "optionalTextChange"; }, never, never, true, [{ directive: typeof i1.ValueAccessorDirective; inputs: {}; outputs: {}; }]>;
}
