import { TemplateRef, ElementRef } from '@angular/core';
import { FormitemComponent } from '../formitem/formitem.component';
import { ValueAccessorDirective } from '../../directives/valueaccessor.directive';
import type { IconType } from '../../types/icons';
import { type IconLinkTarget } from '../iconlink/iconlink.component';
import type { AriaAttributes } from '../../types';
import type { AriaPressedType } from '../button/button.component';
import * as i0 from "@angular/core";
import * as i1 from "../../directives/valueaccessor.directive";
export declare class PasswordComponent extends FormitemComponent {
    readonly valueAccessor: ValueAccessorDirective<string>;
    private configService;
    readonly id: import("@angular/core").InputSignal<string>;
    readonly name: import("@angular/core").InputSignal<string>;
    readonly disabled: import("@angular/core").ModelSignal<boolean>;
    readonly label: import("@angular/core").InputSignal<string>;
    readonly placeholder: import("@angular/core").InputSignal<string>;
    readonly minLength: import("@angular/core").InputSignalWithTransform<number, unknown>;
    readonly maxLength: import("@angular/core").InputSignalWithTransform<number, unknown>;
    readonly required: import("@angular/core").ModelSignal<boolean>;
    readonly showPasswordButtonLabel: import("@angular/core").InputSignal<string>;
    readonly linkTitle: import("@angular/core").InputSignal<string>;
    readonly hasForgotPasswordLink: import("@angular/core").InputSignalWithTransform<boolean, unknown>;
    readonly href: import("@angular/core").InputSignal<string>;
    readonly target: import("@angular/core").InputSignal<IconLinkTarget>;
    readonly toggletip: import("@angular/core").InputSignal<string>;
    readonly toggletipLabel: import("@angular/core").InputSignal<string>;
    readonly toggletipCloseLabel: import("@angular/core").InputSignal<string>;
    readonly toggletipTemplate: import("@angular/core").InputSignal<TemplateRef<unknown>>;
    readonly requiredSign: import("@angular/core").ModelSignal<string>;
    readonly requiredSignTitleAttr: import("@angular/core").InputSignal<string>;
    readonly optionalText: import("@angular/core").ModelSignal<string>;
    readonly visuallyHiddenLabel: import("@angular/core").InputSignalWithTransform<boolean, unknown>;
    readonly ariaAttributes: import("@angular/core").InputSignal<AriaAttributes>;
    readonly autocomplete: import("@angular/core").InputSignal<"current-password" | "new-password">;
    readonly input: import("@angular/core").Signal<ElementRef<any>>;
    protected externalId: string;
    protected type: 'password' | 'text';
    protected iconType: IconType;
    protected showPassword: AriaPressedType;
    protected passwordButtonLabel: string;
    private innerValue?;
    /** Inserted by Angular inject() migration for backwards compatibility */
    constructor(...args: unknown[]);
    protected get containerCssClasses(): string;
    protected get inputAriaAttributes(): AriaAttributes;
    protected get cssElementClass(): string;
    get value(): string;
    set value(value: string);
    protected onFocusout(event: FocusEvent): void;
    protected toggle(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<PasswordComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PasswordComponent, "drv-password", never, { "id": { "alias": "id"; "required": false; "isSignal": true; }; "name": { "alias": "name"; "required": false; "isSignal": true; }; "disabled": { "alias": "disabled"; "required": false; "isSignal": true; }; "label": { "alias": "label"; "required": false; "isSignal": true; }; "placeholder": { "alias": "placeholder"; "required": false; "isSignal": true; }; "minLength": { "alias": "minLength"; "required": false; "isSignal": true; }; "maxLength": { "alias": "maxLength"; "required": false; "isSignal": true; }; "required": { "alias": "required"; "required": false; "isSignal": true; }; "showPasswordButtonLabel": { "alias": "showPasswordButtonLabel"; "required": false; "isSignal": true; }; "linkTitle": { "alias": "linkTitle"; "required": false; "isSignal": true; }; "hasForgotPasswordLink": { "alias": "hasForgotPasswordLink"; "required": false; "isSignal": true; }; "href": { "alias": "href"; "required": false; "isSignal": true; }; "target": { "alias": "target"; "required": false; "isSignal": true; }; "toggletip": { "alias": "toggletip"; "required": false; "isSignal": true; }; "toggletipLabel": { "alias": "toggletipLabel"; "required": false; "isSignal": true; }; "toggletipCloseLabel": { "alias": "toggletipCloseLabel"; "required": false; "isSignal": true; }; "toggletipTemplate": { "alias": "toggletipTemplate"; "required": false; "isSignal": true; }; "requiredSign": { "alias": "requiredSign"; "required": false; "isSignal": true; }; "requiredSignTitleAttr": { "alias": "requiredSignTitleAttr"; "required": false; "isSignal": true; }; "optionalText": { "alias": "optionalText"; "required": false; "isSignal": true; }; "visuallyHiddenLabel": { "alias": "visuallyHiddenLabel"; "required": false; "isSignal": true; }; "ariaAttributes": { "alias": "ariaAttributes"; "required": false; "isSignal": true; }; "autocomplete": { "alias": "autocomplete"; "required": false; "isSignal": true; }; }, { "disabled": "disabledChange"; "required": "requiredChange"; "requiredSign": "requiredSignChange"; "optionalText": "optionalTextChange"; }, never, never, true, [{ directive: typeof i1.ValueAccessorDirective; inputs: {}; outputs: {}; }]>;
}
