/**
 * IBMHackaton-TheLionKing
 * API zur Verarbeitung von PDF-Dokumenten und Ergebnisabfrage.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiError { 
    /**
     * Fehlercode
     */
    code: ApiError.CodeEnum;
    /**
     * Menschlich lesbare Beschreibung.
     */
    message: string;
}
export namespace ApiError {
    export type CodeEnum = 'BAD_REQUEST' | 'NOT_FOUND' | 'SERVER_ERROR';
    export const CodeEnum = {
        BadRequest: 'BAD_REQUEST' as CodeEnum,
        NotFound: 'NOT_FOUND' as CodeEnum,
        ServerError: 'SERVER_ERROR' as CodeEnum
    };
}


