/**
 * IBMHackaton-TheLionKing
 * API zur Verarbeitung von PDF-Dokumenten und Ergebnisabfrage.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubDocument } from './subDocument';


export interface ResultResponse { 
    /**
     * Prozess-ID.
     */
    id: string;
    firstName?: string;
    surname?: string;
    summary?: string;
    vsnr?: string;
    birthDate?: string;
    /**
     * Liste erkannter Subdokumente (inklusive Base64-PDF).
     */
    documents: Array<SubDocument>;
}

