/**
 * IBMHackaton-TheLionKing
 * API zur Verarbeitung von PDF-Dokumenten und Ergebnisabfrage.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StartResponse { 
    /**
     * ID des gestarteten Prozesses.
     */
    readonly id: string;
}

