/**
 * IBMHackaton-TheLionKing
 * API zur Verarbeitung von PDF-Dokumenten und Ergebnisabfrage.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Extrahiertes/klassifiziertes Teil-Dokument mit inline PDF.
 */
export interface SubDocument { 
    /**
     * Base64-kodierte PDF-Daten.
     */
    documentData: string;
    /**
     * Klassifikation des Dokuments.
     */
    category: SubDocument.CategoryEnum;
    /**
     * Erkannter Vorname in diesem Dokument.
     */
    firstName?: string;
    /**
     * Erkannter Nachname in diesem Dokument.
     */
    surname?: string;
    /**
     * Erkannte Versicherungsnummer in diesem Dokument.
     */
    vsnr?: string;
    /**
     * Erkannter Geburtstag (YYYY-MM-DD).
     */
    birthDate?: string;
    /**
     * Zusammenfassung des Dokuments.
     */
    summary?: string;
    /**
     * an json with ai detected headers and values
     */
    additionalFields?: { [key: string]: any; };
}
export namespace SubDocument {
    export type CategoryEnum = 'AUSWEIS' | 'GEBURTSURKUNDE' | 'STERBEURKUNDE' | 'ZEUGNIS' | 'STEUERBESCHEID' | 'KRANKENKASSENBESCHEINIGUNG' | 'SONSTIGE';
    export const CategoryEnum = {
        Ausweis: 'AUSWEIS' as CategoryEnum,
        Geburtsurkunde: 'GEBURTSURKUNDE' as CategoryEnum,
        Sterbeurkunde: 'STERBEURKUNDE' as CategoryEnum,
        Zeugnis: 'ZEUGNIS' as CategoryEnum,
        Steuerbescheid: 'STEUERBESCHEID' as CategoryEnum,
        Krankenkassenbescheinigung: 'KRANKENKASSENBESCHEINIGUNG' as CategoryEnum,
        Sonstige: 'SONSTIGE' as CategoryEnum
    };
}


